default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: product_hunt_clone_development

test:
  <<: *default
  database: product_hunt_clone_test

production:
  <<: *default
  database: product_hunt_clone_production
  username: product_hunt_clone
  password: <%= ENV['PRODUCT_HUNT_CLONE_DATABASE_PASSWORD'] %>
